name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
     
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Doxygen
      run: |
            sudo apt install doxygen
            cd doc && doxygen Doxyfile && cd ..
    - name: make
      run: make
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html
